// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetActiveSessions(ctx context.Context, userID uuid.UUID) ([]UserSession, error)
	GetSession(ctx context.Context, arg GetSessionParams) (UserSession, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
}

var _ Querier = (*Queries)(nil)
